#!/bin/bash

cat >> /opt/cell/cluster/cluster.yaml <<-EOT
docker::install_from_source: false
docker::use_upstream_package_source: true
docker::repo_opt:
  - --disablerepo=*
  - --enablerepo=docker
docker::storage_driver: devicemapper
docker::dm_fs: xfs
EOT

/usr/local/bin/provision puppet docker 00-docker 5
