#!/bin/bash

module_name="10-marathon"
export zk=$(zk-list-nodes)

if [[ -f /opt/cell/etc/roles/stateless-body ]]; then
  cat >>/opt/cell/cluster/cluster.yaml <<-EOT
marathon::zk: zk://$zk/marathon
marathon::master: zk://$zk/mesos
marathon::bin_path: /opt/marathon/bin
marathon::install_java: false
EOT
  provision puppet marathon
else
  report_status "${module_name} skipped"
fi

