#!/bin/bash

export zk=$(zk-list-nodes)
cat >>/opt/cell/cluster/cluster.yaml <<-EOT
mesos::zookeeper:   zk://$zk/mesos
mesos::listen_address: ""
mesos::master::env_var:
  MESOS_work_dir: /var/lib/mesos/master
  MESOS_ip_discovery_command: /usr/local/bin/get_ip
mesos::slave::env_var:
  MESOS_work_dir: /var/lib/mesos/slave
  MESOS_attributes: "role:${cell_role}"
  MESOS_gc_delay: 1days
  MESOS_slave_subsystems: cpu,memory
  MESOS_ip_discovery_command: /usr/local/bin/get_ip
EOT

mkdir -p /var/lib/mesos

if [[ -f /opt/cell/etc/roles/stateless-body ]]; then
  provision puppet mesos,mesos::slave,mesos::master
fi

if [[ -f /opt/cell/etc/roles/stateful-body || -f /opt/cell/etc/roles/membrane ]]; then
  provision puppet mesos,mesos::slave
fi

