#!/bin/bash

module_name="02-mesos"
mesos_port_range="[31000-32000,80,443]" # default port range in Mesos
if [[ -f /opt/cell/etc/roles/stateful-body || -f /opt/cell/etc/roles/stateless-body ]]; then
    mesos_port_range="[4369-4369,8081-32000,80,443]"
fi

export zk=$(zk-list-nodes)
cat >>/opt/cell/cluster/cluster.yaml <<-EOT
mesos::zookeeper: zk://$zk/mesos
mesos::repo: "mesosphere"
mesos::log_dir: "/var/log/mesos"
mesos::master::quorum: 1
mesos::master::env_var:
  MESOS_work_dir: /var/lib/mesos/master
  MESOS_ip_discovery_command: /usr/local/bin/get_ip
mesos::slave::env_var:
  MESOS_work_dir: /var/lib/mesos/slave
  MESOS_attributes: "role:${cell_role}"
  MESOS_resources: "ports(*):${mesos_port_range}"
  MESOS_gc_delay: 1days
  MESOS_slave_subsystems: cpu,memory
  MESOS_ip_discovery_command: /usr/local/bin/get_ip
EOT

# TODO remove after CELL-368
mkdir -p /var/lib/mesos

if [[ -f /opt/cell/etc/roles/stateless-body ]]; then
  provision puppet "base::tuning,mesos,mesos::slave,mesos::master"
elif [[ -f /opt/cell/etc/roles/stateful-body || -f /opt/cell/etc/roles/membrane ]]; then
  provision puppet "base::tuning,mesos,mesos::slave"
else
  report_status "${module_name} skipped"
fi


