#!/bin/bash
# default images mount the first ephemeral disk to /mnt
# this is from cloud-init config that comes with the cloud-init.rpm
umount /mnt
# set timezone
echo "UTC" > /etc/timezone
ln -sf /usr/share/zoneinfo/UTC /etc/localtime
setenforce 0

yum install -y curl wget ruby ruby-devel kpartx parted cifs-utils
wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O /usr/local/bin/jq
chmod +x /usr/local/bin/jq

# install mustache gem for easy templating
gem install mustache
# install pip
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
# Downgrade pip to avoid https://github.com/pypa/pip/issues/3384
pip install --upgrade "certifi==2015.04.28" "pip==8.1.0" "awscli==1.9.21" "pystache==0.5.4" "pyyaml"

source /etc/profile.d/cellos.sh

AWS_ACCESS_KEY_ID="${SAASBASE_ACCESS_KEY_ID}" AWS_SECRET_ACCESS_KEY="${SAASBASE_SECRET_ACCESS_KEY}" aws s3 cp ${repository}/cell-os/seed-${cellos_version}.tar.gz /opt/cell
# attempt to download seed from local bucket as well
[[ "${cell_backend}" == "aws" ]] && aws s3 cp s3://${cell_bucket_name}/${full_cell_name}/shared/cell-os/seed.tar.gz /opt/cell
# unarchive files
mkdir -p /opt/cell/seed
pushd /opt/cell
rm -rf seed
[[ -f seed-${cellos_version}.tar.gz ]] && tar zxf seed-${cellos_version}.tar.gz
[[ -f seed.tar.gz ]] && tar zxf seed.tar.gz
rm -rf seed*.tar.gz
cp -a /opt/cell/seed/bin/* /usr/local/bin
chmod +x /usr/local/bin/*
popd

# export vars
echo "export number_of_disks=$(/usr/local/bin/detect-and-mount-disks)" >> /etc/profile.d/cellos.sh
source /etc/profile.d/cellos.sh

report_status "role ${cell_role}"
report_status "seeds ${cell_modules},zk_barrier"
report_status "${cell_role} start"

[[ -x /usr/local/bin/prepare_${cell_backend} ]] && prepare_${cell_backend}

prepare_seeds

function do_provision {
    for module_path in /opt/cell/seed/*; do
        local provision_script="${module_path}/${1}"
        local module="$(basename $module_path)"
        if [[ "$cell_modules" == *"${module}"* ]]; then
            if [[ -x "${provision_script}" ]]; then
                report_status "${module} start"
                "${provision_script}" || {
                    report_status "${module} failed"
                    error_exit "Failed to deploy ${module}"
                }
                report_status "${module} end"
            fi
        fi
    done
}

# execute pre
do_provision provision

# wait for zk
report_status "zk_barrier start"
/usr/local/bin/zk-barrier
export zk=`zk-list-nodes 2>/dev/null`
report_status "zk_barrier end"

# execute post
do_provision provision_post

report_status "${cell_role} end"
success_exit

exit 0

